# Generated by Django 2.1.7 on 2019-04-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex07', '0003_auto_20190401_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
